### ISSUE TITLE
s_CoreMappings in CacheSimSetThreadCoreMapping updated incorrectly?

### ISSUE THREAD

**Issue by midnite8177** [InsomniacGames/ig-cachesim#10]
I was just looking through the source code and I think I spotted a bug, but I don't know for sure.

In CacheSim.cpp, in the function CacheSimSetThreadCoreMapping there is the following code:
```
  s_CoreMappings[count].m_ThreadId = thread_id;
  s_CoreMappings[logical_core_id].m_LogicalCore = logical_core_id;

  ++s_CoreMappingCount;
```
Should this be?:
```
  s_CoreMappings[count].m_ThreadId = thread_id;
  s_CoreMappings[count].m_LogicalCore = logical_core_id;

  ++s_CoreMappingCount;

```

**Comment by midnite8177** [comment]
Furthermore, shouldn't the 'for' loop in CacheSimSetThreadCoreMapping break out if it found the same thread being updated that is already mapped? The way it currently is written it will keep adding new entries to s_CoreMapping, even if you are just trying to update a thread's core id.

**Comment by deplinenoise** [comment]
I suspect you're right on both counts. Care to put together a patch?
