### ISSUE TITLE
TLS reads not working on linux

### ISSUE THREAD

**Issue by falconcruise** [InsomniacGames/ig-cachesim#11]
The instruction "mov %fs:(%rax),$rbx" causes the debugbreak in data_r (CacheSim.cpp) to fail due to a negative address. I haven't had a chance to dig into the state further to see where the problem came from.

The input buffer is
0x64 0x48 0x8b 0x18 0x48 0x85 0xdb 0x0f
0x84 0x90 0x00 0x00 0x00 0xbe 0x01 0x00

%rbx is 0x1c
%rax is 0xffffffffffffffa0

**Comment by deplinenoise** [comment]
Good catch. The problem seems to be that we're not compensating for non-default segments in `ComputeEa` at all. I think what we'd need to do is switch on the segments involved and add in the segment base for `fs`, assuming that `cs` and `ds` are at their default null base.
