### ISSUE TITLE
CacheSimInternals.h(73): 'operator ==': 3 overloads have similar conversions

### ISSUE THREAD

**Issue by wonkoRT** [InsomniacGames/ig-cachesim#3]
When compiling with VS2015 and Qt5.8.0 I'm getting the compilation error below.
It can be resolved by changing
    `static_assert((kSetCount & (~size_t(kSetMask))) == kSetCount,     "Set count must be power of 2");`
to
    `static_assert((kSetCount & (~size_t(kSetMask))) == size_t(kSetCount),     "Set count must be power of 2");`

> 3>...\ig-cachesim\cachesim\CacheSimInternals.h(73): error C2666: 'operator ==': 3 overloads have similar conversions
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qpagelayout.h(93): note: could be 'bool operator ==(const QPageLayout &,const QPageLayout &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qpagesize.h(248): note: or       'bool operator ==(const QPageSize &,const QPageSize &)'
> 3>         ...\qt\qt5.8.0\5.8\msvc2015_64\include\qtgui\qopenglcontext.h(113): note: or       'bool operator ==(const QOpenGLVersionProfile &,const QOpenGLVersionProfile &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qopenglversionfunctions.h(106): note: or       'bool operator ==(const QOpenGLVersionStatus &,const QOpenGLVersionStatus &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qquaternion.h(279): note: or       'bool operator ==(const QQuaternion &,const QQuaternion &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qvector4d.h(232): note: or       'bool operator ==(const QVector4D &,const QVector4D &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qvector3d.h(232): note: or       'bool operator ==(const QVector3D &,const QVector3D &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qsurfaceformat.h(156): note: or       'bool operator ==(const QSurfaceFormat &,const QSurfaceFormat &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qaccessible.h(443): note: or       'bool operator ==(const QAccessible::State &,const QAccessible::State &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qevent.h(820): note: or       'bool operator ==(QPointingDeviceUniqueId,QPointingDeviceUniqueId) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qevent.h(793): note: or       'bool operator ==(QKeySequence::StandardKey,QKeyEvent *)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qevent.h(792): note: or       'bool operator ==(QKeyEvent *,QKeySequence::StandardKey)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtGui/qvector2d.h(207): note: or       'bool operator ==(const QVector2D &,const QVector2D &)'
> 3>         ...\qt\qt5.8.0\5.8\msvc2015_64\include\qtcore\qstorageinfo.h(99): note: or       'bool operator ==(const QStorageInfo &,const QStorageInfo &)'
> 3>         ...\qt\qt5.8.0\5.8\msvc2015_64\include\qtcore\qrect.h(853): note: or       'bool operator ==(const QRectF &,const QRectF &) noexcept'
> 3>         ...\qt\qt5.8.0\5.8\msvc2015_64\include\qtcore\qrect.h(454): note: or       'bool operator ==(const QRect &,const QRect &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qsize.h(339): note: or       'bool operator ==(const QSizeF &,const QSizeF &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qsize.h(169): note: or       'bool operator ==(const QSize &,const QSize &) noexcept'
> 3>         ...\qt\qt5.8.0\5.8\msvc2015_64\include\qtcore\qmetaobject.h(201): note: or       'bool operator ==(const QMetaMethod &,const QMetaMethod &)'
> 3>         ...\qt\qt5.8.0\5.8\msvc2015_64\include\qtcore\qmargins.h(372): note: or       'bool operator ==(const QMarginsF &,const QMarginsF &) noexcept'
> 3>         ...\qt\qt5.8.0\5.8\msvc2015_64\include\qtcore\qmargins.h(135): note: or       'bool operator ==(const QMargins &,const QMargins &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qversionnumber.h(310): note: or       'bool operator ==(const QVersionNumber &,const QVersionNumber &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qpoint.h(348): note: or       'bool operator ==(const QPointF &,const QPointF &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qpoint.h(163): note: or       'bool operator ==(const QPoint &,const QPoint &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qvariant.h(567): note: or       'bool operator ==(const QVariant &,const QVariantComparisonHelper &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qhash.h(139): note: or       'bool operator ==(const QHashDummyValue &,const QHashDummyValue &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1678): note: or       'bool operator ==(const QByteArray &,const QStringRef &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1671): note: or       'bool operator ==(const QStringRef &,const QByteArray &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1662): note: or       'bool operator ==(QLatin1String,QChar) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1643): note: or       'bool operator ==(const QStringRef &,QChar) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1624): note: or       'bool operator ==(const QString &,QChar) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1605): note: or       'bool operator ==(const QStringRef &,QLatin1String) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1598): note: or       'bool operator ==(QLatin1String,const QStringRef &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1573): note: or       'bool operator ==(const QStringRef &,const QString &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1566): note: or       'bool operator ==(const QString &,const QStringRef &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1554): note: or       'bool operator ==(const QStringRef &,const QStringRef &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1217): note: or       'bool operator ==(const char *,QLatin1String)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1160): note: or       'bool operator ==(QLatin1String,QLatin1String) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1155): note: or       'bool operator ==(const QString &,QString::Null)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1154): note: or       'bool operator ==(QString::Null,const QString &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1153): note: or       'bool operator ==(QString::Null,QString::Null)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1651): note: or       'bool operator ==(QChar,QLatin1String) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1632): note: or       'bool operator ==(QChar,const QStringRef &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1613): note: or       'bool operator ==(QChar,const QString &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1699): note: or       'bool operator ==(const char *,const QStringRef &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(1204): note: or       'bool operator ==(const char *,const QString &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qstring.h(648): note: or       'bool operator ==(const QString &,const QString &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qbytearray.h(607): note: or       'bool operator ==(const char *,const QByteArray &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qbytearray.h(605): note: or       'bool operator ==(const QByteArray &,const char *) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qbytearray.h(603): note: or       'bool operator ==(const QByteArray &,const QByteArray &) noexcept'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qchar.h(573): note: or       'bool operator ==(QChar,QChar) noexcept'
> 3>         C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\shared\guiddef.h(192): note: or       'bool operator ==(const GUID &,const GUID &)'
> 3>         ...\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qchar.h(586): note: or       'std::enable_if<std::is_same<remove_cv<>::type,int>::value,bool>::type operator ==<>(QChar,T) noexcept'
> 3>                 with
> 3>                 [
> 3>                     T=
> 3>                 ]
> 3>         ...\ig-cachesim\cachesim\CacheSimInternals.h(73): note: while trying to match the argument list '(std::size_t, )'
> 3>         ...\ig-cachesim\cachesim\CacheSimInternals.h(142): note: see reference to class template instantiation 'CacheSim::Cache<kCacheSizeBytes,kWays>' being compiled
>

**Comment by deplinenoise** [comment]
Yeah it's annoying. I have a fix for it outside the repo I'll push out on Monday.

**Comment by deplinenoise** [comment]
In the mean time you can work around it by commenting out the static asserts or adding a bunch of casts.
